# Generated by Django 5.2.7 on 2025-10-08 15:55

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP')),
                ('secondary_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_id', models.CharField(max_length=100, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP')),
                ('customer_secondary_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP')),
                ('customer_address', models.TextField()),
                ('total_weight', models.CharField(choices=[('0-0.2', '0-0.2'), ('0.2-0.5', '0.2-0.5'), ('0.5-1', '0.5-1'), ('1-1.5', '1-1.5'), ('1.5-2', '1.5-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-6', '4-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9'), ('9-10', '9-10'), ('10-11', '10-11'), ('11-12', '11-12'), ('12-13', '12-13'), ('13-14', '13-14'), ('14-15', '14-15')], default='pending', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.store')),
            ],
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name'], name='app_store_name_2ab3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['phone'], name='app_store_phone_70fdbd_idx'),
        ),
    ]
