# Generated by Django 5.2.7 on 2025-10-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='contact_person',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
