# Generated by Django 5.2.7 on 2025-10-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_item_description_order_special_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consignment_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
