# Generated by Django 5.2.7 on 2025-10-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_order_consignment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned for Delivery'), ('transit', 'In Transit'), ('hold', 'on Hold'), ('delivery', 'Delivery'), ('partial_delivery', 'Partial Delivery'), ('exchange', 'Exchange'), ('returned', 'Returned'), ('paid_return', 'Paid Return'), ('return_transit', 'Return In Transit'), ('return_assigned', 'Assigned for Return'), ('return_to_merchant', 'Return To Merchant'), ('cancelled', 'Cancelled')], default='pending', max_length=100),
        ),
    ]
